package com.cardinalstar.cubicchunks.worldgen.ccenhanced.surface;

import javax.annotation.ParametersAreNonnullByDefault;

import net.minecraft.init.Blocks;
import net.minecraft.world.World;
import net.minecraft.world.chunk.storage.ExtendedBlockStorage;

import com.cardinalstar.cubicchunks.worldgen.ccenhanced.biome.BiomeLookupResult;
import com.cardinalstar.cubicchunks.worldgen.ccenhanced.biome.CCBiomeGenBase;
import com.cardinalstar.cubicchunks.worldgen.ccenhanced.terrain.ColumnContext;
import com.gtnewhorizon.gtnhlib.util.data.ImmutableBlockMeta;

/**
 * Paints biome-appropriate surface blocks (top, filler) onto terrain generated by
 * CCTerrainGenerator, and fills ocean areas below sea level with still water.
 *
 * <p>
 * Operates on a 16-entry EBS array (index = cubeY, range 0–15). Missing entries are
 * created on demand (e.g. for water that sits above an air-region ocean floor).
 */
@ParametersAreNonnullByDefault
public class CCSurfacePainter {

    private static final int SEA_LEVEL = 64;

    /**
     * Paints surface blocks and fills water into the EBS array for a single chunk column.
     * Modifies {@code ebsArray} in-place; entries may be created for water-fill cubes.
     *
     * @param world    world instance (for hasNoSky when allocating EBS)
     * @param ebsArray 16-entry array indexed by cubeY (0–15); entries may be null
     * @param ctx      column context from CCTerrainGenerator
     * @param grid     5×5 biome grid from CCBiomeCache for this chunk
     */
    public void paint(World world, ExtendedBlockStorage[] ebsArray, ColumnContext ctx, BiomeLookupResult[] grid) {
        for (int bx = 0; bx < 16; bx++) {
            for (int bz = 0; bz < 16; bz++) {
                int sy = ctx.getSurfaceY(bx, bz);
                CCBiomeGenBase biome = grid[bz << 4 | bx].primary;

                paintSurface(world, ebsArray, bx, bz, sy, biome);
                fillWater(world, ebsArray, bx, bz, sy);
            }
        }
    }

    // -------------------------------------------------------------------------
    // Internals
    // -------------------------------------------------------------------------

    /** Places ccTopBlock at surfaceY-1 and ccFillerBlock for the next fillerDepth blocks below. */
    private void paintSurface(World world, ExtendedBlockStorage[] ebsArray, int bx, int bz, int sy,
        CCBiomeGenBase biome) {
        int topY = sy - 1;
        if (topY < 0 || topY >= 256) return;

        setBlock(world, ebsArray, bx, topY, bz, biome.ccTopBlock);

        for (int i = 1; i <= biome.fillerDepth; i++) {
            int y = topY - i;
            if (y < 0) break;
            setBlock(world, ebsArray, bx, y, bz, biome.ccFillerBlock);
        }
    }

    /** Fills still water from surfaceY up to SEA_LEVEL-1 for below-sea columns. */
    private void fillWater(World world, ExtendedBlockStorage[] ebsArray, int bx, int bz, int sy) {
        if (sy >= SEA_LEVEL) return;
        int waterBottom = Math.max(0, sy);
        for (int y = waterBottom; y < SEA_LEVEL; y++) {
            int cubeY = y >> 4;
            int localY = y & 0xF;
            ExtendedBlockStorage ebs = getOrCreate(world, ebsArray, cubeY);
            ebs.func_150818_a(bx, localY, bz, Blocks.water);
        }
    }

    /** Sets a block+meta at world-Y y, allocating EBS if needed. */
    private void setBlock(World world, ExtendedBlockStorage[] ebsArray, int bx, int y, int bz, ImmutableBlockMeta bm) {
        int cubeY = y >> 4;
        int localY = y & 0xF;
        if (cubeY < 0 || cubeY >= ebsArray.length) return;

        ExtendedBlockStorage ebs = getOrCreate(world, ebsArray, cubeY);
        ebs.func_150818_a(bx, localY, bz, bm.getBlock());
        int meta = bm.getBlockMeta();
        if (meta != 0) {
            ebs.setExtBlockMetadata(bx, localY, bz, meta);
        }
    }

    /** Returns the EBS at cubeY, creating an empty one if currently null. */
    private ExtendedBlockStorage getOrCreate(World world, ExtendedBlockStorage[] ebsArray, int cubeY) {
        if (ebsArray[cubeY] == null) {
            ebsArray[cubeY] = new ExtendedBlockStorage(cubeY * 16, !world.provider.hasNoSky);
        }
        return ebsArray[cubeY];
    }
}
